env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier

overrides: []

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
  - import

rules:
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  func-style:
    - error
    - expression
  react/function-component-definition:
    - warn
    - namedComponents: arrow-function
  react/react-in-jsx-scope: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  '@typescript-eslint/no-empty-function': off
  react/self-closing-comp:
    - error
    - component: true
      html: true
  padding-line-between-statements:
    - error
    - blankLine: never
      prev: const
      next: const
    - blankLine: always
      prev: import
      next: const
    - blankLine: always
      prev: multiline-const
      next: multiline-const
    - blankLine: always
      prev: const
      next: multiline-const
    - blankLine: always
      prev: multiline-const
      next: const
    - blankLine: always
      prev: '*'
      next: export
    - blankLine: always
      prev: '*'
      next: return
  import/order:
    - error
    - groups:
        - builtin
        - external
        - parent
        - sibling
        - index
        - object
        - type
      pathGroups:
        - pattern: '{react,react-dom/**,react-router-dom}'
          group: builtin
          position: before
        - pattern: '{@atoms/**,@molecules/**,@organisms/**,@pages/**,@utils/**,@locales/**}'
          group: parent
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
      'newlines-between': always
      singleQuotes: true
