import json
import os

import boto3


def lambda_handler(event, context):
    try:
        user_id = context.identity.cognito_identity_id
        date = event["queryStringParameters"]["date"]

        # Fetch item from DynamoDB
        title = get_title_from_dynamodb(user_id, date)

        if title:
            return {
                "statusCode": 200,
                "body": json.dumps({"title": title}),
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*",
                },
            }
        else:
            return {
                "statusCode": 200,
                "body": json.dumps({"title": ""}),
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*",
                },
            }
    except Exception as e:
        return {
            "statusCode": 400,
            "body": json.dumps(f"An error occurred: {str(e)}"),
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*",
            },
        }


def get_title_from_dynamodb(user_id, date):
    """Get title using user_id and date from dynamodb

    Args:
        user_id (string): user id from cognito userpool 
        date (string): date of the diary entry

    Returns:
        title (string): title generated by chatGPT

    """
    dynamodb = boto3.resource("dynamodb")
    table_name = os.environ["TABLE_NAME"]
    table = dynamodb.Table(table_name)

    try:
        response = table.get_item(Key={"user_id": user_id, "date": date})

        if "Item" in response:
            return response["Item"].get("title")
        else:
            return None
    except Exception as e:
        print(f"Error fetching data from DynamoDB: {e}")
        return None
