name: Lint

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Nodeのセットアップ
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # npmキャッシュの復元
      - name: Restore npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            src/backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # BiomeでLint
      - name: Biome Lint
        run: npx run lint ./src
