name: Lint

# ワークフローが呼び出された場合にのみ実行
on:
  workflow_call:

# デフォルトのシェルをbashに設定
defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # npmキャッシュの復元
      - name: Restore npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'packages/*/package-lock.json') }}

      # BiomeでLint
      - name: Biome Lint
        run: npm run lint .
