name: Python ruff

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

# デフォルトのシェルをbashに設定
defaults:
  run:
    shell: bash

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ryeのインストール
      - name: Install a specific version
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"

      # Ryeを使用してRuffをインストール
      - name: Install Ruff
        run: |
          rye install ruff

      # Ruffを使用してLintを実行
      - name: Run Ruff Check
        run: |
          rye run ruff check src/

      # Ruffを使用してフォーマットチェックを実行
      - name: Run Ruff Format Check
        run: |
          rye run ruff format --check src/
