name: example

on:
  push:

jobs:
  s3ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1' # リージョンを指定
          role-to-assume: 'arn:aws:iam::851725642854:role/diary-dev-test-morimoto-actions-role'

      # プライベートな S3 バケットを読み取ってみる
      - run: aws s3 ls s3://diaryhostingbucket