name: Tests

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Pythonの依存関係の復元
      - name: Restore pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Test with pytest
        run: |
          pytest

      # Nodeのセットアップ
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # npmキャッシュの復元
      - name: Restore npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            src/backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: CDK Test
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: npx -w src/backend npm run test
